taxomachine build tweaks

diff --git a/roles/launch-otc-ws-app/templates/launch_otc_ws_app_sh.j2 b/roles/launch-otc-ws-app/templates/launch_otc_ws_app_sh.j2
--- a/roles/launch-otc-ws-app/templates/launch_otc_ws_app_sh.j2
+++ b/roles/launch-otc-ws-app/templates/launch_otc_ws_app_sh.j2
@@ -15,9 +15,9 @@ export LD_LIBRARY_PATH="{{ ws_dir }}/installed/library:${LD_LIBRARY_PATH}"
     "-D{{ otc_ws_data }}/synth_trees" \
     "-p{{ otc_ws_data }}/wspidfile.txt" \
     -P1984 \
-    --num-threads=4 \
-    --prefix=v3
+    --num-threads=4
 
+nt=0
 while true ; do
     sleep 1
     if test -f "{{ otc_ws_data }}/wspidfile.txt" ; then
@@ -27,4 +27,9 @@ while true ; do
     if ! pgrep otc-tol-ws >/dev/null ; then
         echo "otc-tol-ws could not be launched"
     fi
+    if test $nt -gt 30 ; then
+        echo "otc-tol-ws not launched after 15 seconds, aborting..."
+        exit 2
+    fi
+    nt=$(expr $nt + 1)
 done
